### PR TITLE
Replace tabs with spaces

### LINKED ISSUE #199: Tab vs. Space Policy
Do we have a policy for this?

We seem to be inconsistent. A search through the repo shows:
```
<space><space><space><space> found in 141 files
\tab found in 22 files
```

@bwohlberg @Michael-T-McCann

### PR DESCRIPTION
**Pull request by bwohlberg**
Replace tabs with spaces. Resolves #199.

### CODE REVIEW

**Comment by tbalke** [comment]
Only these? I am getting:

```
/Users/thilobalke/pythonModules/scico/.gitmodules
/Users/thilobalke/pythonModules/scico/.github/isbin.sh
/Users/thilobalke/pythonModules/scico/docs/Makefile
/Users/thilobalke/pythonModules/scico/docs/source/notes.rst
/Users/thilobalke/pythonModules/scico/docs/source/optimizer.rst
/Users/thilobalke/pythonModules/scico/docs/source/references.bib
/Users/thilobalke/pythonModules/scico/docs/source/style.rst
/Users/thilobalke/pythonModules/scico/examples/scriptcheck.sh
/Users/thilobalke/pythonModules/scico/misc/conda/install_conda.sh
/Users/thilobalke/pythonModules/scico/misc/conda/make_conda_env.sh
```

**Comment by bwohlberg** [comment]
I don't think that really matters, but I've replaced the tabs in all but `docs/source/references.bib`, which will have to remain as it is since the emacs bibtex mode uses tabs for formatting.

**Comment by tbalke** [comment]
> I don't think that really matters, but I've replaced the tabs in all but `docs/source/references.bib`, which will have to remain as it is since the emacs bibtex mode uses tabs for formatting.

Odd, I am still getting 42 hits in:
```
examples/scriptcheck.sh
misc/conda/install_conda.sh
misc/conda/make_conda_env.sh
```

**Comment by bwohlberg** [comment]
I removed the tabs used `sed`, but they must have been re-introduced by `emacs` when I fixed the indentation. Consider shell scripts as added to the "won't fix" list for this.

**Review by tbalke — APPROVED** [review]

**Pull request merged**
