### PR TITLE
add check for A not linop in prox

### PR DESCRIPTION
**Pull request by tbalke**
See #215

Note that check for `self.has_prox`, namely that `W` is `Diagonal`, was redundant and so I removed it.

### CODE REVIEW

**Comment by tbalke** [comment]
In `test_functional.py` we get the following functions failing:
```python
    def test_squared_l2(self):
        L = loss.SquaredL2Loss(y=self.y, A=self.Ao)
        assert L.has_eval == True
        assert L.has_prox == False  # not diagonal

    def test_weighted_squared_l2(self):
        L = loss.WeightedSquaredL2Loss(y=self.y, A=self.Ao, W=self.W)
        assert L.has_eval == True
        assert L.has_prox == False  # not diagonal
```
with
```
        assert L.has_eval == True
>       assert L.has_prox == False  # not diagonal
E       AssertionError: assert True == False
E        +  where True = <class 'scico.loss.WeightedSquaredL2Loss'>\nhas_eval = True\nhas_prox = True\n        .has_prox
```

However, `self.Ao` is a `LinearOperator` so in this case we indeed have a prox. Why are we asserting that `has_prox` is `False`?

**Comment by bwohlberg** [comment]
> Note that check for `self.has_prox`, namely that `W` is `Diagonal`, was redundant and so I removed it.

In what way was it redundant?

**Comment by tbalke** [comment]
> > Note that check for `self.has_prox`, namely that `W` is `Diagonal`, was redundant and so I removed it.
> 
> In what way was it redundant?

We had
```python
if isinstance(self.A, linop.Diagonal) and isinstance(self.W, linop.Diagonal):
    self.has_prox = True
```

At this point `isinstance(self.W, linop.Diagonal) == True` always because we set it to a `Diagonal` in case it is `None`.

**Comment by bwohlberg** [comment]
> At this point `isinstance(self.W, linop.Diagonal) == True` always because we set it to a Diagonal in case it is None.

But what if `W` is not `None`, but is set to something other than a `linop.Diagonal`?

**Comment by tbalke** [comment]
> > At this point `isinstance(self.W, linop.Diagonal) == True` always because we set it to a Diagonal in case it is None.
> 
> But what if `W` is not `None`, but is set to something other than a `linop.Diagonal`?

Then `raise TypeError(f"W must be None or a linop.Diagonal, got {type(W)}")`

**Comment by bwohlberg** [comment]
> However, `self.Ao` is a `LinearOperator` so in this case we indeed have a prox. Why are we asserting that `has_prox` is `False`?

Previously (some months ago), the prox was only defined if the linear operator was diagonal. That changed when you (I think) added a CG solution for non-diagonal case. I would have assumed that this test was a remnant from before, but that doesn't explain why it only started failing now.

**Comment by bwohlberg** [comment]
> > But what if `W` is not `None`, but is set to something other than a `linop.Diagonal`?
> 
> Then `raise TypeError(f"W must be None or a linop.Diagonal, got {type(W)}")`
> 
> So it is either `Diagonal` or `None` in which case we set it to `Identity` which is a `Diagonal`

OK, that makes sense. The full context is not apparent in the diff!

**Comment by tbalke** [comment]
> > However, `self.Ao` is a `LinearOperator` so in this case we indeed have a prox. Why are we asserting that `has_prox` is `False`?
> 
> Previously (some months ago), the prox was only defined if the linear operator was diagonal. That changed when you (I think) added a CG solution for non-diagonal case. I would have assumed that this test was a remnant from before, but that doesn't explain why it only started failing now.

Correct. I think that the test fails because this is not an appropriate test. I suggest changing the test to the negation. If the A is a linop then `has_prox` should be true.

**Comment by bwohlberg** [comment]
> Correct. I think that the test fails because this is not an appropriate test. I suggest changing the test to the negation. If the A is a linop then `has_prox` should be true.

That seems reasonable, but I'm a bit concerned that we don't understand why the tests only started failing *now*.

**Comment by tbalke** [comment]
> > Correct. I think that the test fails because this is not an appropriate test. I suggest changing the test to the negation. If the A is a linop then `has_prox` should be true.
> 
> That seems reasonable, but I'm a bit concerned that we don't understand why the tests only started failing _now_.

The previous test asserted that `has_prox == False` (incorrectly) and the loss.py code set the `has_prox` attribute to `False` (incorrectly) when `A` was a linop.

Fixing the loss.py code made fixing the test code necessary.

**Comment by bwohlberg** [comment]
That makes sense w.r.t. tests, but it is a bit strange that we did not previously noticed that the new prox capability that was added was crippled by this oversight. Nevertheless, you may as well go ahead and make the proposed changes to the tests.

**Review by bwohlberg — APPROVED** [review]
Looks good, but let's ask @Michael-T-McCann to take a look too.

**Pull request merged**
