### PR TITLE
Significant docs extension and restructuring

### PR DESCRIPTION
**Pull request by bwohlberg**
Add content that was removed from JOSS paper and restructure TOC for more rational ordering.

### CODE REVIEW

**Comment by bwohlberg** [comment]
`Base Classes` is perhaps not the best title since that section also includes `BlockArray`, which is not primarily intended as a base for derived classes. Any suggestions for alternatives?

**Comment by Michael-T-McCann** [comment]
> `Base Classes` is perhaps not the best title since that section also includes `BlockArray`, which is not primarily intended as a base for derived classes. Any suggestions for alternatives?

I didn't mind "Important Classes." Other options: "Main Classes" "SCICO Classes" "Main SCICO Classes".

**Review by Michael-T-McCann — APPROVED** [review]
Looks like a fine way to incorporate the JOSS material. Consider moving "SCICO Contributors" outside the "User Documentation" section. Could be a part of "Developer Documentation" (a stretch, but no more a stretch than its current location) or a top-level section on its own. Or a subsection at the bottom of "Overview".

**Comment by crstngc** [comment]
> > `Base Classes` is perhaps not the best title since that section also includes `BlockArray`, which is not primarily intended as a base for derived classes. Any suggestions for alternatives?
> 
> I didn't mind "Important Classes." Other options: "Main Classes" "SCICO Classes" "Main SCICO Classes".

I am OK with "Main SCICO Classes" or "Core SCICO Classes".

**Review by crstngc — APPROVED** [review]
This makes a nicer and more comprehensive introduction to SCICO. 

A nit-picking: I would prefer for each of the Base (Main) Classes to have their own page as before.

**Comment by bwohlberg** [comment]
> > `Base Classes` is perhaps not the best title since that section also includes `BlockArray`, which is not primarily intended as a base for derived classes. Any suggestions for alternatives?
> 
> I didn't mind "Important Classes." Other options: "Main Classes" "SCICO Classes" "Main SCICO Classes".

Thanks for the suggestions. I'm inclined to go with "Main SCICO Classes".

**Comment by bwohlberg** [comment]
> A nit-picking: I would prefer for each of the Base (Main) Classes to have their own page as before.

I do see the benefit of each class having its own page. I made the change primarily because the class index page was really ugly, and inconsistent with the style of the rest of the docs. I'm open to suggestions for how to separate them again in a way that avoid the ugly index page.

**Pull request merged**
