### PR TITLE
Update conda install scripts

### PR DESCRIPTION
**Pull request by bwohlberg**
Update conda install scripts:
* Update `jaxlib` version
* Update `astra-toolbox` install method
* Default Python version now 3.9
* Handle additional dependencies for `svmbir` and `bm3d`

### CODE REVIEW

**Review by Michael-T-McCann — CHANGES_REQUESTED** [review]
In my shell (zsh on mac), `./make_conda_env.sh` gives the error 

    ./make_conda_env.sh: line 63: syntax error near unexpected token `&'

**Comment by bwohlberg** [comment]
Almost certainly due to incompatibilities between `zsh` and `bash`. How did you run it? It's intended as a `bash` script, and indicated as such by the initial `#! /bin/bash`.

**Comment by Michael-T-McCann** [comment]
> How did you run it?

The same error occurs when I run it with `bash make_conda_env.sh` or `./make_conda_env.sh`. I believe my bash version is 3.2.

**Comment by bwohlberg** [comment]
> The same error occurs when I run it with `bash make_conda_env.sh` or `./make_conda_env.sh`. I believe my bash version is 3.2.

Indeed, not incompatibility between `zsh` and `bash`, but use of an incredibly old version of bash (4.0 was released in 2009) that does not support the `case` fall through syntax using `;;&`. I added a test for bash 4 to the script.

**Review by Michael-T-McCann — COMMENTED** [review]
I can confirm the script now leads me to update bash. After doing so:

The environment I get fails a bunch of pytests due to `scico.random`, which in turn (I think) is due to the environment giving me jax version 0.2.27 instead of the pinned version 0.2.26.

Why doesn't the workflow catch these pytest failures on 0.2.27? Because of a bug in the workflow, see #189.

**Review by Michael-T-McCann — APPROVED** [review]

**Comment by bwohlberg** [comment]
> The environment I get fails a bunch of pytests due to `scico.random`, which in turn (I think) is due to the environment giving me jax version 0.2.27 instead of the pinned version 0.2.26.

Fixed and tested on OSX with Python 3.9.

**Pull request merged**
